### ISSUE TITLE
Static file settings for prod

### ISSUE THREAD

**Issue by gordonje** [rji-futures-lab/django-rmp-data#84]
The objectives are:

1. To serve static files from an S3 bucket (not from lambda)
2. To allow developers to invoke `collectstatic` from their local machines in add update the production files (without having to edit their settings files and environment variables.

**Comment by gordonje** [comment]
Having trouble at this point using zappa to invoke `collectstatic` from the lambda function:

```
zappa manage dev "collectstatic --noinput"
```

Here is the error I'm getting:

```
ResourceNotExistsError: The 's3' resource does not exist.
The available resources are:
   -
Traceback (most recent call last):
  File "/var/task/handler.py", line 602, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 248, in lambda_handler
    return handler.handler(event, context)
  File "/var/task/handler.py", line 413, in handler
    management.call_command(*event['manage'].split(' '))
  File "/var/task/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/var/task/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/task/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
    collected = self.collect()
  File "/var/task/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    handler(path, prefixed_path, storage)
  File "/var/task/django/contrib/staticfiles/management/commands/collectstatic.py", line 342, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/var/task/django/contrib/staticfiles/management/commands/collectstatic.py", line 249, in delete_file
    if self.storage.exists(prefixed_path):
  File "/var/task/storages/backends/s3boto3.py", line 532, in exists
    self.connection.meta.client.head_object(Bucket=self.bucket_name, Key=name)
  File "/var/task/storages/backends/s3boto3.py", line 315, in connection
    verify=self.verify,
  File "/var/task/boto3/session.py", line 347, in resource
    has_low_level_client)
```

Here's what I've tried so far:

- Invoking `collectstatic` from my local environment and passing in the the prod settings
- Checking the zappa zip package to make sure that boto3, botocore, and storages are all included.
- General frantic toggling and re-configuring or [django-storages](https://github.com/jschneier/django-storages) related settings (although, the first item in this list suggest that isn't the problem).

Might try switching from django-storages to [django-s3-storages](https://github.com/etianen/django-s3-storage). After all, we probably only ever use S3 for storage.

In the meantime, the workaround is to invoke `collectstatic` locally and pass in the prod settings:

```
`python manage.py collectstatic --settings "config.settings.prod" --noinput`
```
